name: "Schema Engine: Deployment"

on:
  workflow_dispatch: {}

jobs:
  generate-matrix:
    name: Scan Contracts Folder
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Build Schema Map
        id: set-matrix
        run: |
          cd schemas
          # -c guarantees a clean, compact single-line JSON string for the matrix
          JSON_ARRAY=$(jq -c --null-input '$ARGS.positional | map({
            subject: (split(".")[0] + "-value"), 
            path: ("schemas/" + .)
          })' --args -- *)
          echo "matrix=${JSON_ARRAY}" >> $GITHUB_OUTPUT

  publish-contracts:
    name: Release
    needs: [generate-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        schema-pair: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    
    env:
      SCHEMA_REGISTRY_URL: ${{ secrets.SR_URL }}
      SCHEMA_REGISTRY_API_KEY: ${{ secrets.SR_API_KEY }}
      SCHEMA_REGISTRY_API_SECRET: ${{ secrets.SR_API_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Register Schema Contract via script
        run: |
          chmod +x ./.scripts/manage-schema.sh
          ./.scripts/manage-schema.sh push "${{ matrix.schema-pair.subject }}" "${{ matrix.schema-pair.path }}"